services:
  web:
    build: .
    image: "${BE_IMAGE}"
    ports:
      - "8000:8000"
    command: gunicorn Blackstick.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
volumes:
  static_volume:
  media_volume:
