
services:
  web:
    build: .
    command: gunicorn Blackstick.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/dent/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    networks:
      - internal
  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always
    networks:
      - internal
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=blackstick

volumes:
  postgres_data:

networks:
  internal: