###########
# NPM     #
###########

FROM node:20-slim AS npm_builder
WORKDIR /app
COPY static/package.json static/package-lock.json ./
RUN npm ci --omit=dev

###########
# BUILDER #
###########

FROM python:3.12-slim-bookworm AS builder

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
  && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

COPY ./requirements.txt .
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/app/wheels -r requirements.txt


#########
# FINAL #
#########

FROM python:3.12-slim-bookworm

RUN mkdir -p /home/app

RUN addgroup --system app && adduser --system --group app

ENV HOME=/home/app \
    APP_HOME=/home/app/web

RUN mkdir $APP_HOME \
    && mkdir $APP_HOME/staticfiles \
    && mkdir $APP_HOME/mediafiles

WORKDIR $APP_HOME

RUN apt-get update && apt-get install -y --no-install-recommends \
    netcat-openbsd \
    libpq5 \
    gettext \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libcairo2 \
    libgdk-pixbuf-2.0-0 \
    libffi8 \
    fontconfig \
    fonts-dejavu-core \
  && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/app/wheels /wheels
COPY --from=builder /usr/src/app/requirements.txt .
RUN pip install --upgrade pip \
    && pip install --no-cache /wheels/*

COPY . $APP_HOME

COPY --from=npm_builder /app/node_modules $APP_HOME/static/node_modules/

RUN sed -i 's/\r$//g' $APP_HOME/entrypoint.prod.sh \
    && chmod +x $APP_HOME/entrypoint.prod.sh \
    && chown -R app:app $APP_HOME

USER app

ENTRYPOINT ["/home/app/web/entrypoint.prod.sh"]
