# Generated by Django 4.2.6 on 2024-02-25 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='staff',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_clinic', to='dent.clinic'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='cr_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_crby', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='cr_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
