# Generated by Django 4.2.6 on 2024-02-25 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0002_remove_servicecategory_staff_servicecategory_clinic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dent.servicecategory')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_staff', to='dent.staff')),
            ],
        ),
    ]
