# Generated by Django 4.2.6 on 2024-08-16 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dent', '0004_servicecategory_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='ServiceCategory',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='StaffServiceCategory',
        ),
        migrations.AddField(
            model_name='servicestaff',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs_service', to='dent.service'),
        ),
        migrations.AddField(
            model_name='servicestaff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs_name', to='dent.staff'),
        ),
    ]
