# Generated by Django 4.2.6 on 2024-10-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0005_servicestaff_rename_servicecategory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='currency',
            field=models.CharField(default='SOM', max_length=3),
        ),
    ]
