# Generated by Django 5.1.2 on 2025-06-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0007_alter_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
