# Generated by Django 5.1.2 on 2025-02-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='initial_price',
        ),
        migrations.AddField(
            model_name='providerserverservice',
            name='service_private_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
