# Generated by Django 5.1.2 on 2025-02-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0002_remove_servicetype_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='server',
        ),
    ]
