# Generated by Django 5.1.2 on 2025-02-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0003_remove_service_server'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='providerserverservice',
            unique_together={('provider_server', 'service')},
        ),
    ]
