# Generated by Django 5.1.2 on 2025-02-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0004_alter_providerserverservice_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
