# Generated by Django 5.1.2 on 2025-02-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0005_provider_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='identifier',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
