# Generated by Django 5.1.2 on 2025-02-23 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0006_alter_provider_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booket.provider')),
            ],
        ),
    ]
