# Generated by Django 5.1.2 on 2025-02-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0007_providerphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerserver',
            name='off_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
