# Generated by Django 5.1.2 on 2025-03-01 16:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0008_providerserver_off_days'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('full_name', 'phone_number')},
        ),
        migrations.RemoveField(
            model_name='weekschedule',
            name='off_days',
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='ProviderClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booket.client')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booket.provider')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='service_provider',
        ),
    ]
