# Generated by Django 5.1.2 on 2025-03-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0009_alter_client_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeekSchedule',
        ),
    ]
