# Generated by Django 5.1.2 on 2025-03-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0012_alter_client_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='providerclient',
            constraint=models.UniqueConstraint(fields=('provider', 'client'), name='unique_provider_client'),
        ),
    ]
