# Generated by Django 5.1.2 on 2025-03-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0013_providerclient_unique_provider_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW'), ('CONFIRMED', 'CONFIRMED'), ('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('CANCELLED', 'CANCELLED'), ('REJECTED', 'REJECTED'), ('COMPLETED', 'COMPLETED')], max_length=12, null=True),
        ),
    ]
