# Generated by Django 5.1.2 on 2025-03-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0014_client_comments_client_is_active_client_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='language_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
