# Generated by Django 5.1.2 on 2025-03-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0015_client_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='verification_method',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
