# Generated by Django 5.1.2 on 2025-03-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0016_otpverification_verification_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
