# Generated by Django 5.1.2 on 2025-03-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0017_appointment_created_on'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_client_email',
        ),
    ]
