# Generated by Django 5.1.2 on 2025-03-20 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0018_remove_client_unique_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='client',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booket.appointment'),
        ),
    ]
