# Generated by Django 5.1.2 on 2025-03-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0019_remove_otpverification_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
