# Generated by Django 5.1.2 on 2025-03-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0020_server_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='title',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW'), ('CONFIRMED', 'CONFIRMED'), ('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('CANCELLED', 'CANCELLED'), ('REJECTED', 'REJECTED'), ('NO_SHOW', 'NO_SHOW'), ('COMPLETED', 'COMPLETED')], max_length=12, null=True),
        ),
    ]
