# Generated by Django 5.1.2 on 2025-04-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0021_remove_appointment_title_alter_appointment_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'end_datetime', 'created_on'], name='booket_appo_status_72eed7_idx'),
        ),
    ]
