# Generated by Django 5.1.2 on 2025-04-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0022_appointment_booket_appo_status_72eed7_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='sms_message_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='sms_request_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='sms_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='sms_status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
