# Generated by Django 5.1.2 on 2025-05-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0023_otpverification_sms_message_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_client_name_phone',
        ),
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_client_phone',
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', False), ('phone_number__isnull', False), _connector='OR'), name='at_least_one_contact_info_required'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), ('phone_number__isnull', False)), fields=('email', 'phone_number'), name='unique_email_and_phone_when_both_provided'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number__isnull', True), ('email__isnull', False)), fields=('email',), name='unique_email_when_phone_is_null'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', True), ('phone_number__isnull', False)), fields=('phone_number',), name='unique_phone_when_email_is_null'),
        ),
    ]
