# Generated by Django 5.1.2 on 2025-06-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0024_remove_client_unique_client_name_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='footer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='phone_numbers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='social_media',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='specialists_section_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='specialists_section_text_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
