# Generated by Django 5.1.2 on 2025-07-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0025_provider_footer_text_provider_phone_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
