# Generated by Django 5.1.2 on 2025-07-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0026_alter_provider_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
