# Generated by Django 5.1.2 on 2025-07-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0027_server_title_server_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
