# Generated by Django 5.1.2 on 2026-04-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0031_appointment_comment_by_server_appointmentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
