# Generated by Django 5.1.2 on 2026-05-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0033_provider_add_lat_lng'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['server', 'start_datetime', 'status'], name='booket_appo_server__a237aa_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='booket_clie_email_15c261_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['phone_number'], name='booket_clie_phone_n_ef4106_idx'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['is_verified', 'created_at'], name='booket_otpv_is_veri_07854d_idx'),
        ),
    ]
