# Generated by Django 5.1.2 on 2026-05-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0034_add_indexes_client_otp_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
