# Generated by Django 5.1.2 on 2026-06-19 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_invoice_last_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='orders.paymentrecord'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('ORDER', 'Buyurtma'), ('PAYMENT', "To'lov kvitansiyasi")], default='ORDER', max_length=20),
        ),
    ]
