# Generated by Django 5.1.2 on 2026-07-05 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_payment_balance_after_and_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='landing_slides/%Y/%m/')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_slides', to='orders.supplier')),
            ],
            options={
                'verbose_name': 'Landing slayd',
                'verbose_name_plural': 'Landing slaydlar',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
