name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Build, tag and publish
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: django-ec2
          IMAGE_TAG: latest
        run: |
          docker buildx build --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . --push

      - name: Pull and Run
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_REMOTE_URI: ${{ steps.login-ecr.outputs.registry }}/django-ec2
        run: |
          echo "${{ secrets.SSH_KEY }}" > dev.key
          chmod 600 dev.key
          cat dev.key
          echo "Imported the KEY"
          scp -i dev.key -o StrictHostKeyChecking=no docker-compose.prod.yml ubuntu@${{ secrets.INSTANCE_IP_ADDRESS }}:./
          echo "Copied the yaml file"
          ssh -i dev.key -o StrictHostKeyChecking=no ubuntu@${{ secrets.INSTANCE_IP_ADDRESS }} << "ENDSSH"
            echo "In SSH block"
            ls
            aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
            aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            aws configure set region "us-east-1"
            aws configure set output "text"
            aws ecr get-login-password --region us-east-1 | docker login -u AWS --password-stdin ${{ env.ECR_REGISTRY }}
            docker pull ${{ env.IMAGE_REMOTE_URI }}:latest
          ENDSSH